#########################################################################
#									#
# File ID: ./.travis.yml						#
# Author: Copyright (C) 2019  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0					#
#									#
# Configuration file for Travis CI build tests.				#
#									#
#########################################################################

#########################################################################
#									#
# Changelog								#
#									#
# Date		Author	Version	Description				#
#									#
# 22/06/2019	MG	1.0.1	Initial release.                        #
#									#
#########################################################################


language: java

dist:
    - xenial

before_install:
    - sudo add-apt-repository ppa:m-grant-prg/utils -y
    - sudo apt-get update
    - sudo apt-get install -y autoconf-archive util-linux
    - sudo apt-get install -y libgetopt-java
    - sudo apt-get install -y txt2man txt2manwrap

script:
    - autoreconf -if .
    - ./configure --enable-silent-rules=yes --enable-atonly=yes
    - make --quiet
    - make --quiet check
    - make --quiet distcheck

